import { v2 as cloudinary, type UploadApiOptions, type UploadApiResponse } from "cloudinary";

import { env } from "@/config/env";

// ─── Configuration ────────────────────────────────────────────────────────────

cloudinary.config({
  cloud_name: env.CLOUDINARY_CLOUD_NAME,
  api_key: env.CLOUDINARY_API_KEY,
  api_secret: env.CLOUDINARY_API_SECRET,
  secure: true,
});

// ─── Types ────────────────────────────────────────────────────────────────────

/** The two Cloudinary folder paths used in this project. */
export type CloudinaryFolder = "images" | "pdfs";

/** Folder → full Cloudinary path mapping. */
export const CLOUDINARY_FOLDERS: Record<CloudinaryFolder, string> = {
  images: "sadiqul-islam-shakib/images",
  pdfs: "sadiqul-islam-shakib/pdfs",
};

/**
 * Metadata returned after a successful upload.
 * Used to populate the `asset_file` table row.
 */
export interface UploadedAssetMeta {
  cloudinaryPublicId: string;
  folder: CloudinaryFolder;
  url: string;
  resourceType: "image" | "raw" | "video";
  format: string;
  bytes: number;
  width?: number;
  height?: number;
  checksum: string; // SHA-256 hex, provided by caller — stored for deduplication
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Detect resource_type from folder:
 *   - "pdfs" folder → "raw"  (Cloudinary treats non-image binary files as raw)
 *   - "images" folder → "image"
 */
function folderToResourceType(
  folder: CloudinaryFolder
): "image" | "raw" | "video" {
  return folder === "pdfs" ? "raw" : "image";
}

// ─── Core Functions ───────────────────────────────────────────────────────────

/**
 * Upload a file to Cloudinary.
 *
 * @param source   - A file path, URL, base64 data URI, or Buffer.
 * @param folder   - "images" | "pdfs" — determines the Cloudinary subfolder.
 * @param checksum - SHA-256 hex digest of the file (generated by caller).
 *                   Stored in asset_file for deduplication validation.
 * @param publicId - Optional custom public_id. Auto-generated if omitted.
 *
 * @returns UploadedAssetMeta to persist in the `asset_file` table.
 *
 * @example
 * // In an API route handler:
 * const checksum = await computeSHA256(buffer);
 * const existing = await db.query.assetFile.findFirst({ where: eq(assetFile.checksum, checksum) });
 * if (existing) { ... reuse existing asset_file ... }
 * const meta = await uploadAsset(buffer, "images", checksum);
 */
export async function uploadAsset(
  source: string | Buffer,
  folder: CloudinaryFolder,
  checksum: string,
  publicId?: string
): Promise<UploadedAssetMeta> {
  const resourceType = folderToResourceType(folder);
  const cloudinaryFolder = CLOUDINARY_FOLDERS[folder];

  const uploadOptions: UploadApiOptions = {
    folder: cloudinaryFolder,
    resource_type: resourceType,
    use_filename: true,
    unique_filename: true,
    overwrite: false,
    ...(publicId ? { public_id: publicId } : {}),
  };

  let result;
  if (Buffer.isBuffer(source)) {
    // Upload from Buffer via a data URI conversion
    result = await new Promise<UploadApiResponse>(
      (resolve, reject) => {
        const uploadStream = cloudinary.uploader.upload_stream(
          uploadOptions,
          (error, result) => {
            if (error || !result) reject(error ?? new Error("Upload failed"));
            else resolve(result);
          }
        );
        uploadStream.end(source);
      }
    );
  } else {
    result = await cloudinary.uploader.upload(source, uploadOptions);
  }

  // Cloudinary returns an empty/null format for raw (PDF) uploads.
  // Fall back to the last segment of the resource_type or folder name.
  const resolvedFormat =
    result.format && result.format.length > 0
      ? result.format
      : folder === "pdfs"
      ? "pdf"
      : "bin";

  return {
    cloudinaryPublicId: result.public_id,
    folder,
    url: result.secure_url,
    resourceType: result.resource_type as "image" | "raw" | "video",
    format: resolvedFormat,
    bytes: result.bytes,
    width: result.width ?? undefined,
    height: result.height ?? undefined,
    checksum,
  };
}

/**
 * Replace an existing Cloudinary asset.
 *
 * Destroys the old file by `publicId`, then uploads the new file.
 * Returns the metadata for the new file to update the `asset_file` row.
 *
 * ⚠️  This invalidates the Cloudinary CDN cache for the old public_id.
 *     If you need the old URL to remain valid (e.g. another asset_file
 *     references it), do NOT call this — upload a new asset instead.
 *
 * @param oldPublicId - Cloudinary public_id of the file to remove.
 * @param newSource   - New file: path, URL, base64 URI, or Buffer.
 * @param folder      - "images" | "pdfs"
 * @param checksum    - SHA-256 of the new file.
 *
 * @returns UploadedAssetMeta for the newly uploaded file.
 */
export async function replaceAsset(
  oldPublicId: string,
  newSource: string | Buffer,
  folder: CloudinaryFolder,
  checksum: string
): Promise<UploadedAssetMeta> {
  // Destroy old file first
  const resourceType = folderToResourceType(folder);
  await cloudinary.uploader.destroy(oldPublicId, {
    resource_type: resourceType,
    invalidate: true, // purge CDN cache
  });

  // Upload new file
  return uploadAsset(newSource, folder, checksum);
}

/**
 * Remove a file from Cloudinary by its public_id.
 *
 * Call this when deleting an `asset_file` row to also clean up the
 * Cloudinary storage.
 *
 * @param publicId     - Cloudinary public_id of the file.
 * @param folder       - "images" | "pdfs" — used to infer resource_type.
 * @param invalidate   - Whether to purge the CDN cache (default: true).
 *
 * @returns Cloudinary deletion result ({ result: "ok" | "not found" }).
 */
export async function removeAsset(
  publicId: string,
  folder: CloudinaryFolder,
  invalidate = true
): Promise<{ result: string }> {
  const resourceType = folderToResourceType(folder);
  const result = await cloudinary.uploader.destroy(publicId, {
    resource_type: resourceType,
    invalidate,
  });
  return result as { result: string };
}

/**
 * Get a Cloudinary asset's details by public_id.
 * Useful for verifying an asset exists before database operations.
 */
export async function getAssetDetails(
  publicId: string,
  folder: CloudinaryFolder
) {
  const resourceType = folderToResourceType(folder);
  return cloudinary.api.resource(publicId, {
    resource_type: resourceType,
  });
}

/**
 * Build an optimized Cloudinary URL with transformation options.
 *
 * @example
 * buildCloudinaryUrl("sadiqul-islam-shakib/images/quantipixor-og", { width: 800, quality: "auto", format: "auto" })
 */
export function buildCloudinaryUrl(
  publicId: string,
  options: {
    width?: number;
    height?: number;
    quality?: string | number;
    format?: string;
    crop?: string;
  } = {}
): string {
  return cloudinary.url(publicId, {
    secure: true,
    transformation: [
      {
        width: options.width,
        height: options.height,
        quality: options.quality ?? "auto",
        fetch_format: options.format ?? "auto",
        crop: options.crop ?? "fill",
      },
    ],
  });
}

// ─── Export configured client ─────────────────────────────────────────────────

export { cloudinary };
