export const FrameIoDesignTokens = {
  colors: {
    carbonVellum: '#fcfcfc',
    obsidian: '#0a0a13',
    pitch: '#000000',
    void: '#040407',
    graphite: '#08080c',
    smoke: '#757580',
    ash: '#a3a3b3',
    charcoal: '#2a2a32',
    irisGlow: '#6199f6',
    twilight: '#4f4f80',
    specterLilac: '#dedfee',
  },
  typography: {
    fonts: {
      times: '"Times", ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
      frameGothic: '"FrameGothic", "Inter", ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
      neueMachinaInktrap: '"NeueMachinaInktrap", "Space Mono", ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
      arial: '"Arial", ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    },
    scale: {
      caption: { size: '12px', lineHeight: '1.45', letterSpacing: '0.72px' },
      bodySm: { size: '14px', lineHeight: '1.5', letterSpacing: 'normal' },
      body: { size: '16px', lineHeight: '1.45', letterSpacing: '0.16px' },
      subheading: { size: '18px', lineHeight: '1.3', letterSpacing: 'normal' },
      headingSm: { size: '24px', lineHeight: '1.25', letterSpacing: '-0.72px' },
      heading: { size: '38px', lineHeight: '1.04', letterSpacing: '-1.33px' },
      headingLg: { size: '48px', lineHeight: '1.02', letterSpacing: '-1.92px' },
      display: { size: '80px', lineHeight: '0.96', letterSpacing: '-3.6px' },
    },
    weights: {
      regular: 400,
      medium: 500,
      semibold: 600,
    }
  },
  spacing: {
    unit: '8px',
    '8': '8px',
    '16': '16px',
    '24': '24px',
    '32': '32px',
    '40': '40px',
    '48': '48px',
    '56': '56px',
    '80': '80px',
    '96': '96px',
    '144': '144px',
    '160': '160px',
    '176': '176px',
  },
  layout: {
    pageMaxWidth: '1280px',
    sectionGap: '80px',
    cardPadding: '24px',
    elementGap: '24px',
  },
  borderRadius: {
    sm: '1px',
    lg: '10px',
    '3xl': '24px',
    full: '100px',
    nav: '100px',
    cards: '10px',
    pills: '100px',
    buttons: '100px',
    dividers: '1px',
    featureCards: '24px',
  },
  surfaces: {
    cosmicCanvas: '#0a0a13',
    navVeil: '#040407',
    productSurface: '#08080c',
    cardHalo: '#181826',
  }
};
